// src/helpers/eventsData.ts
import { IEvent } from "@/interface/types";

export const getEventsData = (language: "nl" | "en"): IEvent[] => [
  {
    id: 1,
    date: "2025-06-04",
    title: language === "nl" ? "Syrische Avond" : "Syrian Evening",
    country: language === "nl" ? "Syrië" : "Syria",
    cuisine: language === "nl" ? "Levantijns" : "Levantine",
    chefs: ["Amira", "Bassam"],
    food: "Dessert",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
  },
  {
    id: 2,
    date: "2025-07-05",
    title: language === "nl" ? "Eritrees Feest" : "Eritrean Feast",
    country: language === "nl" ? "Eritrea" : "Eritrea",
    cuisine: language === "nl" ? "Oost-Afrikaans" : "East African",
    chefs: ["Senait", "Tekle"],
    food: "Dessert",
    imageUrl: "https://images.unsplash.com/photo-1567360425618-1594206637d2?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
  },
  {
    id: 3,
    date: "2025-06-04",
    title: language === "nl" ? "Afghaanse Keuken" : "Afghan Kitchen",
    country: language === "nl" ? "Afghanistan" : "Afghanistan",
    cuisine: language === "nl" ? "Centraal-Aziatisch" : "Central Asian",
    chefs: ["Farid", "Laila"],
    food: "Dinner",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
  },
  {
    id: 4,
    date: "2025-07-05",
    title: language === "nl" ? "Marokkaanse Smaken" : "Moroccan Flavors",
    country: language === "nl" ? "Marokko" : "Morocco",
    cuisine: language === "nl" ? "Noord-Afrikaans" : "North African",
    chefs: ["Yasmine", "Karim"],
    food: "Dinner",
    imageUrl: "https://images.unsplash.com/photo-1541518763069-e7f6216e8da5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
  },
  {
    id: 5,
    date: "2025-06-04",
    title: language === "nl" ? "Iraakse Tradities" : "Iraqi Traditions",
    country: language === "nl" ? "Irak" : "Iraq",
    cuisine: language === "nl" ? "Mesopotamisch" : "Mesopotamian",
    chefs: ["Zainab", "Ahmed"],
    food: "Starter",
    imageUrl: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
  },
  {
    id: 6,
    date: "2025-07-05",
    title: language === "nl" ? "Somalische Specialiteiten" : "Somali Specialties",
    country: language === "nl" ? "Somalië" : "Somalia",
    cuisine: language === "nl" ? "Oost-Afrikaans" : "East African",
    chefs: ["Ayan", "Omar"],
    food: "Starter",
    imageUrl: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80",
  },
];